/* Generated By:JavaCC: Do not edit this line. ParserCAMLConstants.java */
package uniandes.teolen.parserJavaCC.myParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserCAMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 5;
  /** RegularExpression Id. */
  int MINUSCULA = 6;
  /** RegularExpression Id. */
  int MAYUSCULA = 7;
  /** RegularExpression Id. */
  int NAME = 8;
  /** RegularExpression Id. */
  int BASICTYPE = 9;
  /** RegularExpression Id. */
  int ATRIBUTE = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"type\"",
    "<MINUSCULA>",
    "<MAYUSCULA>",
    "<NAME>",
    "<BASICTYPE>",
    "<ATRIBUTE>",
    "\"=\"",
    "\";;\"",
    "\"\\\'\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"{\"",
    "\":\"",
    "\";\"",
    "\"}\"",
  };

}
