/* Generated By:JavaCC: Do not edit this line. SimpleLexerConstants.java */
package uniandes.teolen.parserJavaCC.myParserDR;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TOK = 5;
  /** RegularExpression Id. */
  int AT = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int OP = 8;
  /** RegularExpression Id. */
  int CP = 9;
  /** RegularExpression Id. */
  int OB = 10;
  /** RegularExpression Id. */
  int CB = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int PP = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"token\"",
    "\"@\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"::\"",
    "<INT>",
    "<DIGIT>",
  };

}
